import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import ToasterContext from "./context/ToasterContext";

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'MessageApp',
  description: 'Generated by me lol',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <ToasterContext />
        {children}
      </body>
    </html>
  );
}
